version: '3'

services:
  cec_control_MAMA_ROOM:
    image: docker_cec_control:latest
    restart: always
    networks:
      - docker_net
    ports:
      - "3001:3001"
    environment:
      CEC_CONTROL_HOST: "cec_control_MAMA_ROOM"
      CEC_CONTROL_PORT: "3001"
      CEC_CONTROL_NAME: "MAMA_ROOM"
    devices:
      - "/dev/vchiq:/dev/vchiq"

networks:
  docker_net:
    driver: bridge
    ipam:
      driver: default

